### ISSUE TITLE
RatInABox custom Gym environment for RL 

### ISSUE THREAD

**Issue by Matkicail** [TomGeorge1234/RatInABox#30]
Hi,

Your repo is really cool and the visuals are excellent. However, when going through the RL example section, I find that although the example is decent, it still leaves a lot of the skeleton showing (in terms of all the direct stuff you do with the environment and the agent). I would really like to give PPO with an intrinsic curiosity module a go, since your environment is quite interesting. Specifically, to see what the rat would do if only rewarded with curiosity vs the environment reward and curiosity. It would be also be interesting to see if it has rat-like exploration and what would happen if the reward was as sparse as possible (e.g a reward for only reaching the reward square). 

However, it feels a bit difficult to interact with it and get something like that working immediately. Mainly because the environment is not making use (at least in this case https://github.com/TomGeorge1234/RatInABox/blob/1.x/demos/reinforcement_learning_example.ipynb) of the standard Markov Decision Process abstraction. If you had this abstraction, I think it would be super cool since it makes it much easier to try out a variety of RL methods quickly and easily on the task, as it cleanly separates the RL part and your environment.

Not sure if this is a useful suggestion, but if it is I would be super keen to interact with the environment if it has this modification given how cool and interesting your repo looks.

**Comment by SynapticSage** [comment]
... slightly more functional fork now:

https://github.com/SynapticSage/RatInABox/blob/task_environments/ratinabox/contribs/TaskEnvironment.py

**Comment by TomGeorge1234** [comment]
Nice! I'm very impressed, just took a look and it seems really nice so I'm excited to have a play around. At some point perhaps would be great to PR this into the main branch but I'll leave some comments once I've taken a look and leave this thread open in the meantime. 

Appreciate the legwork !

**Comment by SynapticSage** [comment]
Awesome. Ya comments would be appreciated.  Not mature enough for a PR. Maybe eventually. 

Top priority---my guess--would be figuring out how the agent should interface and register a controller for its actions to its member environment. Gymnasium environments store an observation space and an action space as attributes. And the action_space attribute can be a list/dict of action spaces for the registered agents who belong to the task. 

But the main rub is that action spaces themselves, I imagine, could be based on different things. E.g. `drift_velocity` in your script. And then there's something upstream of the controller pulling the strings of the controller, e.g. an agent/neuron. And may need some brainstorming on how to organize interfacing up a given action_space to a agent's controller to variables within {agents, neurons, other-things}.

**Comment by TomGeorge1234** [comment]
Yeah, I think I see. To me it seems quite natural that the state space should be a concatenation of the current firing rates of a list of RatInABox `Neurons`. So if the `Agent` has some `PlaceCells` and `GridCells` its state is entirely determined by the firing rates of those two populations (and nothing else). The action space should be, as you say, `drift_velocity` (and perhaps the ratio parameter determining drift-to-random motion proportions, since this is kind of close to $\epsilon$ in $\epsilon$-greedy it may be more of a hyperparameter). 

Happy to jump on a call some time if it would help, keen to get this off the ground and I'm aware of other people who would use this functionality!

**Comment by SynapticSage** [comment]
For sure -- think I'm on the same page. Makes total sense neurons should provide the input for the action space for obvious reasons---and the focus of your package. Was only probing if there was an appetite for knobs for other moments of inertia or general input from other objects.

Pushed some updates. There's an action space (assuming `drift_velocity` knobs) for each agent, reward, and a loop invoking Gymnasium's step() paradigm.

**Comment by TomGeorge1234** [comment]
_Really_ like where this is going. I ran the code, it works great! Some thoughts: 

* **Continuous time** : We should make the time continuous so on each `update()` there are two updates: `self.time += self.dt` (defaulting to say 0.01) and `self.steps += 1`. The spirit of RiaB is very much to treat time and space continuous...a departure from classic RL where time is a more abstract thing.
* **Handy RiaB geometry funcs** There's a useful (if poorly named) function called `Env.get_distance_between___accounting_for_environment(pos1, pos2,wall_geometry="line_of_sight")`...this does as it says on the tin and will return very large number if there is a wall obstructing the straight line path between `pos1` and `pos2`. This will be necessary in the future to leverage full flexibility of RiaB environments with complex wall structures.
* **Aesthetics** Is it possible to maintain consistency with RiaB plotting functions? i.e. use `Agent.plot_trajectory()`. I'm suspecting maybe this wouldn't be easy as you are doing this efficiently by resetting (rather than replotting) the data each time, nice work btw. I wouldn't die on this hill but I would like to maintain aesthetic consistency where possible. It might help if I restructured how plotting works and wrote a function which returns a matplotlib `LineCollection`. Lmk. 
* **Multiple Agents** I really like that you can have multiple Agents. I'm aware this is probably a faff for you to handle but please keep going with it! By the way, wouldn't this be better handled by [petting zoo](https://pettingzoo.farama.org/content/basic_usage/) (I'm no expert here!). Also has `gym` been replaced with `gymnasium` - if so we should switch for future-proofing. 
* **1D** On the other hand, very happy for you to let go of maintaining functionality in 1D Environments, at least for now. :)))
* **Action space**
Lastly in terms of the action space. I sort of agree with your pseudo code above ^ except it should be more general. Whilst it could be something like `SomeNeurons.drift_velocity()`...in theory it could be something more complex e.g. actor-critic `SomeActorTrainedBySomeOtherPackageInterfacingWithThisGym.drift_velocity()` or PPO or Q-learning whatever ! The example I gave of linear ValueFunction ascent is pretty basic and ultimately quite limiting.

**Comment by SynapticSage** [comment]
- Continous time and geometry funcs: Great suggestion! I hadn't considered these yet. I have now implemented the changes.

- Aesthetics : This might be feasible. `render()` already calls environment's plot and could call those plots first to initialize the line collections. I'll see if it's quick to implement.

Further down the line, you might however consider having each object (environment, agent) be responsible for implementing its own render(), ie cache its own plot objects. It's potentially strange having a task environment cache plot objects about non-task environment features?

If so, I imagine instead a scheme where someone calls the environment's`env.render()` after `env.step`. Whereon, inside the environment's `render()`, `env` would call `render()` on any object that contains which implements its own `render`, and so on... `render()`ing down a cascade of objects. More concretely here, `render()` would call `Agent.render()` and `Objective.render()`. And then those objects **could** in turn survey for any objects they have with `render()`and call those. Maybe even in some cases neurons attached to agents have a `render()` method turned on to plot inside the `env.step(); env.render()` loop.

- Multiple agents: To me I was imagining someone will eventually want to study social vector cells or social tasks at some point; maybe RiAB could help with that. Not tricky to allow---basically just an extra loop. 

- gym/gynasium: I'm behind the  times. I learned how to use gym in 2019. Didn't know that openai moved its functionality to gymnasium. Seems to keep the same interface as far I can tell. Good points. Wouldn't want the objects calling deprecated code. 

- Same story for petting zoo: it arrived after my last brush with the API, to my knowledge.

- Reward: Great ideas! The reward pulses were just a quick n' dirty implementation win. Will check it out.

- Action space: 🙂 Had meant as more of an example as opposed to prescription. Aware.

**Comment by TomGeorge1234** [comment]
Ok, I will definitely consider restructuring some of the plotting stuff (seems like each `Agent` and `Environment` classes could have an internal `_render()` function which plots everything it needs to and returns all matplotlib plot object. The `plot_trajectory()` or whatever function would then just set the data on all these objects. Its a medium sized change however and not essential so for now lets presume to work around it. 

Maybe worth looking into petting zoo. I don't know if it would streamline the multiagent stuff, presumably they built it for a reason 🤷🏼‍♂️

Nice progress though! keep me updated how things get on, looking forward to having it complete!

**Comment by SynapticSage** [comment]
Excellent. Ya, no rush on the `_render()`. It's fine without it.

Pushed some changes aligning the code with `pettingzoo` yesterday
- `step` works as expected for the multi-agent case. 
-  It's potentially annoying to work with dicts of actions per agent for single-agent environments, so added a `step1()` wrapper function that makes the task environment behave like `gymnasium`. `step1` is short for "step with 1 agent". Cuts all the boilerplate and fluff associated with mutli-agent---if people are into that.

Generalizing the `reward` structure next: Provisioned some structure for it. Plan is to attach one cache object containing an agent's active rewards to the environment and put a reference to that same cache inside the agents. That way rewards can be triggered externally from the environment or internally from the neurons that are part of the agent.

**Comment by SynapticSage** [comment]
Posted an update with non-sparse rewards. Have a few features that decide a reward's dynamics:
- initial value
- decay rate for the reward from the initial value (linear, constant, exponential)
- follower term that can be used to attach a ramping signal or goal gradient to a reward
- expiration time: how long does the reward stay active from the moment it appears. `None` means that the reward never expires, but follows its gradient and decay dynamics.

**Comment by TomGeorge1234** [comment]
Awesome!! Happy to see such rapid progress progress being made. Thanks for upgrading to pettingzoo, I see what you mean about it being a bit annoying for single agents but your solution seems good. And also thanks for updating the plotting stuff, really nice :)) 

I like the reward flexibility here - both being able to have multiple rewards and agent or environment dependent rewards. Seems sensible that rewards can be environment, not agent, specific in the cases that multiple agents are competing for the same external rewards. It's also really nice how the rewards can be set on each trial and are stored in a growing cache and expire after a set amount of time. 

Could you please clarify to me the difference/connection between `Objective`s and `Reward`s. I'm a tiny bit confused about the causality here. Objectives just determine the conditions for ending a trial but are they linked to the rewards? As I understand it, each time an `Environment` is reset new goal positions are sample each defining a spatial `Objective`. Does this then trigger the creation of a `Reward` object which gets added to the cache?

**Comment by SynapticSage** [comment]
Ya, no worries. Happy to clarify! Not particularly married to this scheme if its awkward.

The `Objective` represents a specific task rule or condition that must be fulfilled to solve the task. When an agent meets an `Objective`, the `Objective` may **optionally** release a `Reward` object. A task episode consists of a list of `Objective`, and the episode ends when all `Objective`s are completed. In this way, `Objective`s represent a collective terminal state.

Now, a task environment would allow having one without the other: you could create a rule without a reward or create a reward without a rule. In other words, a user constructing a task could **choose** to release elicit `Reward`/(punishment) without an `Objective` or vice-versa. An objective is, if anything, just an organizing class to build a task rule. I imagine if people contribute different tasks (as they do neurons) to RiAB, objectives from different tasks could be mixed and matched to make new tasks. 

When an environment `reset()`s, the env replenishes a list of `Objective` from a pool of potential objectives for a task episode. This is controlled by how users design the `reset()` for their task; it could be as random or deterministic the task maker would like.

 If it's too tricky---totally fine if someone wants to lump `Reward/Objective` into a single object. Slightly more configurable and amenable to polymorphism as separate objects, but I could see there being more boilerplate and cognitive load on the programmer to remember.

**Comment by SynapticSage** [comment]
Commit from earlier this week.

    `Objective` and `Goal` have similar semantic feelings ---a 
    potential source of confusion. Additionally, `Objective` could 
    be wrongfully confused by the user as the objective function of 
    some RL or otherwise algorithm running the agents. Hence, I 
    refactored everything clarify; `Objective` has been changed to 
    `Goal`, which cleans up semantics.
    
    ----------
    New object 
    ----------

    Similar to how `RewardCache` tracks a collection of rewards, 
    `GoalCache` now tracks a collection of goals. In particular, 
    how one or many agents can interact with them. Some things it 
    can handle for the user:
    - do goals have to be completed in sequence? or does order 
      not matter?
    - Does each agent have to finish a given goal? Or is it 
      consumed by another agent?

    `GoalCache` is basically a fancy goal list that handles 
    tracking how agents satisfy goals under those differing 
    schemata.

Still a few bugs to be ironed out. Hoping that object relations read/feel a little more intuitive and clean now.

**Comment by TomGeorge1234** [comment]
Very happy with this. It makes sense that rewards and objectives (now goals) should be disentangled as in reality they needn't be one-to-one. At the end of the day some kind of demo and readme/doc will be necessary to explain all this to end users (as it isn't. trivial) but we can cross that bridge when we come to it. The flexibility you've coded into this will pay off in the long run; as it stands (once bug etc. are ironed out) this could account for so many spatial behaviour set-ups, very impressed. 

I thought I'd share this here so others can see the progress made so far: 

https://user-images.githubusercontent.com/41446693/231140004-9a408a29-0a7c-4801-82a8-b8e68c0cb02e.mov

**Comment by SynapticSage** [comment]
Totally agree that the `TaskEnvironment`, `Goal`, and `Reward` objects might not be trivial for users to quickly grasp. Creating a markdown document doc file with illustrations will make it much easier to comprehend---learning tools from comment headers can be challenging.

Currently, there are some bugs and untested features:
- `goalorder` = `sequence` (bug)
- `agentmode` = `noninteracting` (untested)
- a couple reward-related options (untested)

Busy lab week ri now; I will try to address these on Friday/Saturday, possibly set some pytests. After which, I imagine it might be ready to document and PR into RiAB.

Awesome---glad that things are coming together.

**Comment by SynapticSage** [comment]
Bugs ironed out. Maybe best to transition to documentation/PR soon.

**Comment by TomGeorge1234** [comment]
Brilliant! Feel free to PR when you feel it's ready. As this is a standalone script the requirements for inclusion aren't too high and we can carry on ironing out bugs once it's live.

**Comment by TomGeorge1234** [comment]
Hi @SynapticSage how is this coming along? Reckon it will be ready for a PR some time soon?

**Comment by SynapticSage** [comment]
Apologies for the delay. Hectic month; PR fell off my radar. 

I'll submit it this weekend. Code is operational, but the tutorial needs a little more info here and there. I'll be continuing to refine it after the PR -- as suggested.

Thanks for your patience!

**Comment by TomGeorge1234** [comment]
No worries, was just checking everything was fine. Definitely happy for you to continue to refine it afterwards, much better that way

**Comment by TomGeorge1234** [comment]
Closing as this has now been pushed to contribs. Thanks!

**Comment by TomGeorge1234** [comment]
Hi Ryan! I would like to make a `SpatialGoalEnvironment` where there is a short delay after completing the spatial goal before the episode terminates, this is to allow the Agent to experience the temporally extended reward - otherwise I'm concerned that the reward will be experienced in the following episode (where, here, I'm teleporting the agent to a new location) and credit misattributed. What's the best way to do this?

**Comment by SynapticSage** [comment]
Just shot over a PR for this. Nice QOL improvements: do think the code formatting could use standards. 

So sans the PR, one could just add an unrewarded timer() goal at the end of the goal sequence. 

But since this is a super common need (e.g. for ISIs), just added a shortcut TaskEnvironment attribute `delay_episode_terminate`. It's more or less accomplished by padding an unrewarded timer goal when agents finish their episode goals.

**Comment by SynapticSage** [comment]
The side question:

Yes, unfortunately. It's a `pettingzoo` attribute. `pettingzoo` expects this variable to track the active agents (those who are still able to receive actions during the episode). I wasn't originally planning to have that, but had to add it to appease the pettingzoo environment tests.

**Comment by SynapticSage** [comment]
Absolutely! `env.t`. Totally my mistake. Was distracted while I was typing that part out.

Regarding the reward, you can also give it a `None` object instead of `no_reward_default`, but maybe it's nice to be explicit.

**Comment by TomGeorge1234** [comment]
Oh, a `None` object is way cleaner I prefer that.

**Comment by SynapticSage** [comment]
Sounds good. Goal setting a link to itself in the reward was a relatively recent change. Must have broken the `None` option.

Will try to resurrect it next PR.
