### ISSUE TITLE
RatInABox2.0 - Opening the discussion

### ISSUE THREAD

**Issue by TomGeorge1234** [TomGeorge1234/RatInABox#60]
I've begun to think about 2.0. The reason is that there are are certainly a couple of choices I made early on in development which weren't optimal. Now could be a good time to fix these as the community is growing but still small enough it won't be super disruptive. Also fixing them will make it easier to maintain RiaB in the long run. 

I'm opening this issue to get community thoughts on this. @SynapticSage @colleenjg @jquinnlee @mehulrastogi you're some of the most active users I know fairly well so I'm tagging you to get your input (if you have any), but _anyone_ can chip in here. 

Here's my thoughts:
* **Args not Dicts**: It's increasingly annoying me that parameters are always handed in as dicts. This is unconventional and has warranted very-well-made but hacky work-arounds e.g. #38 #39 
* **Plotting**: To me at least the visualisation ability of RiaB is really important but animations are slow and I like animating things so this annoying. Could improve by being smarter about how we render stuff in matplotlib, and not re-rendering the Environment or trajectories each frame. Stuff like that. See #54 
* **Type hinting**: This is a new thing in python which I've been told to consider. Any thoughts? 
* **Refactoring**: As discussed in #58 #55. E.g. it's not nice having all `Neurons` classes in one `.py` file. 
* **Documentation**: Would be great to have a sustainable ReadTheDocs page. #36 
* **Unit testing**: I have been pretty sloppy about this but will add loads more. 
* **Global Environment `update()`**: Given, now, `Environments` know about their `Agents` and `Agents` know about their `Neurons` we could have just one update function in `Env` which cascades through else thing else. Cleaner? 
* **Jax compatibility**: Very on the fence about this one. Probably leaning towards not doing it. Would be great to have speed ups, autograd and gpu capacity but it could be just a bit too much / unnecessary / off-putting for non-python geeks (tbh, like me). But if jax is the future I want to consider it. Options include: 
    * Don't do to 
    * Partial jax to hit a few heavy-lifting utils functions. Q: Does this even work, would converting to/from jax arrays not be inconveniently slow here? 
    * Full jax no numpy. `np`--> `jnp` everywhere.
    * Both jax and numpy. Users choose which backend. This should hard but I've played around and probably could be done. Has complications though.
* **Modularity** Break down some of the larger `update()` perhaps adding into new agent/neuron/env specific utils scripts.  
* **Testing on PRs** Run RiaB tests, test doc strings and text styling. 
* ...? 

I'm not a massive software guy so @SynapticSage @mehulrastogi feel free to give high level comments about best way to go forward.

**Comment by SynapticSage** [comment]
###  args, not dicts ✅
a helpful case study in support of args  ...

Most of you (I'm sure) have seen Grant Sanderson's beautiful 3blue1brown YouTube channel. Grant impressively homebrewed a piece of software `manim` (math animation engine) that he uses to make his stunning videos.

`manim` actually started out using a `CONFIG` dict --- reminiscent of this situation 🤔

On a positive note, the CONFIG dict cut down on lines in object __init__; encouraged people to spell out settings in one place.

But on the dark side, dicts required nearly re-coding a lot of Python features handled by kwargs and setting attributes. Ultimately the community fork decided to kill CONFIG dicts in favour of args -- decision convo here:
 https://docs.manim.community/en/stable/changelog/0.2.0-changelog.html

And, it looks like Grant Sanderson's fork is also trying to remove them: https://github.com/3b1b/manim/pull/1932

### plotting 👍

💯 replotting = slow.

... if ratinabox caches plot objects, super recommend scheme we chatted about:
https://github.com/TomGeorge1234/RatInABox/issues/30#issuecomment-1486449726

The TaskEnvironment has a weak version of this feature -- doesn't replot everything and thus renders quickly. But it's pretty hacky in my view that the environment caches things about its agents and goals. In the long-run, it will be more maintainable to have each class in charge of caching its own plot objects rather than having to change master supervisor class's plot every time the children classes change.

### type hinting 👍

Especially easy-to-type variables. 

Tools like `jedi` and `language-server-protocol` offer better code completion for type-hinted variables.

### unit testing  👍

### global environment 👍

Possible suggestion: each RIB class could have a list of children (`environment.childen = [agent, ...]`; `agent.children=[neuron,...]`) may help cascade `.update()` and `.plot()`/`.render()` calls down a hierarchy. and would unify the lingo for distributing update/plot. as opposed to each object having a different attribute name for its "kids".

### Jax 🤷‍♂️

No strong opinions. I usually break into optimization mode when an analysis takes more than a day to finish or if it takes an hour, but I run it 100+ times.

Maybe partial is the right choice? Ease into slowly.

**Comment by colleenjg** [comment]
Sounds like a great idea overall for the longevity of the package! I definitely agree for the **args instead of dicts**, **type hinting** and **unit testing**. For **global environment**, if the cascading update is implemented, I would suggest having a `kwarg` like `cascade=True`, to allow users to opt out, when needed. No strong views on the other sections.

I would suggest an additional section:
**modularity**: Many of the classes have very long methods that chain a lot of complex, separate computations together. When I've created new classes for my own use, e.g., new `Agent` classes, I've had to copy long sections of certain methods that I needed to overwrite, but only partially (for example, for computing an agent's velocity). This can create a lot of code duplication (I think there may already be some for the plotting methods). So, I strongly recommend adding the goal of modularization to the list, i.e., extracting meaningful subparts of class methods and turning them into their own functions, perhaps aggregated into `agent_util.py`, `env_util.py` and `neuron_util.py`, or something like that.

**Comment by TomGeorge1234** [comment]
Great comments, thanks guys. @SynapticSage 3B1B advice heeded! @colleenjg you're right this could be more modular, for example `Agent.update()` is pretty enormous. Breaking these down would make sense so I'll look to do that. Don't expect this anytime soon btw so any new ideas, keep posting them here.

**Comment by TomGeorge1234** [comment]
Thanks for the feedback, closing for now.

**Comment by colleenjg** [comment]
One thing that just occurred to me, which could be considered: 

Only passing `ax` to the plotting functions, not `fig`. 

In typical use cases, to my knowledge, passing both should be redundant, as you can access the figure with `ax.figure` (or `ax.ravel()[0].figure` in cases where `ax` is an array).

**Comment by TomGeorge1234** [comment]
Agreed and added to the list. It's essentially redundant and only add bloat

**Comment by TomGeorge1234** [comment]
@musicinmybrain thanks for your feedback -  that's ok, I doubt we'd go full `jax`. In fact leaning towards no jax at all actually. After some preliminary testing seems like getting significant speed ups would be difficult as most of the heavy computations are already vectorised
